SET sql_log_bin = 0;
-- Create users needed by the sidecar and replication
-- These run on every node via docker-entrypoint-initdb.d

-- Sidecar monitoring user
CREATE USER IF NOT EXISTS 'sidecar'@'%' IDENTIFIED BY 'sidecarpass123';
GRANT SUPER, REPLICATION CLIENT, REPLICATION SLAVE, RELOAD, PROCESS ON *.* TO 'sidecar'@'%';

-- Replication user
CREATE USER IF NOT EXISTS 'replica_user'@'%' IDENTIFIED BY 'replicapass123';
GRANT REPLICATION SLAVE ON *.* TO 'replica_user'@'%';

-- Application user (with full DB access)
CREATE USER IF NOT EXISTS 'banco_app'@'%' IDENTIFIED BY 'bancopass123';
GRANT ALL PRIVILEGES ON banco_db.* TO 'banco_app'@'%';

FLUSH PRIVILEGES;

-- Wipe the GTIDs generated by mysqld --initialize to prevent divergent GTID histories
RESET MASTER;
